[app]
# The name of your app as displayed in the menu
name = "Hex Launcher"

# The submenu where your app should appear.
# One of: "Badge", "Music", "Media", "Apps", "Games", "Background"
category = "Badge"

[metadata]
# Your nickname.  Must be at most 32 characters!
author = "Sam Machin"

# License of your app as an SPDX identifier: <https://spdx.org/licenses/>
license = "MIT"

# URL to the repository of your app.
url = "https://www.github.com/sammachin/HexLauncher"

# Description of your app.  Maximum 140 characters!
description = "A  tildagon app for finding hexpansions with EEPROMS and lauching their apps"

# Version number of your app.  If you push a commit where this number is
# increased, we interpret this as a new version being released.
#
# Version number must be an string!
version = "0.1.1"
